nautobot_firewall_models/urls.py
"""Django urlpatterns declaration for nautobot_firewall_models app."""

from django.templatetags.static import static
from django.urls import path
from django.views.generic import RedirectView
from nautobot.apps.urls import NautobotUIViewSetRouter

from nautobot_firewall_models import views

app_name = "nautobot_firewall_models"
router = NautobotUIViewSetRouter()
router.register("address-object", views.AddressObjectUIViewSet)
router.register("address-object-group", views.AddressObjectGroupUIViewSet)
router.register("application-object", views.ApplicationObjectUIViewSet)
router.register("application-object-group", views.ApplicationObjectGroupUIViewSet)
router.register("capirca-policy", views.CapircaPolicyUIViewSet)
router.register("fqdn", views.FQDNUIViewSet)
router.register("ip-range", views.IPRangeUIViewSet)
router.register("nat-policy", views.NATPolicyUIViewSet)
router.register("nat-policy-rule", views.NATPolicyRuleUIViewSet)
router.register("policy", views.PolicyUIViewSet)
router.register("policy-rule", views.PolicyRuleUIViewSet)
router.register("service-object", views.ServiceObjectUIViewSet)
router.register("service-object-group", views.ServiceObjectGroupUIViewSet)
router.register("user-object", views.UserObjectUIViewSet)
router.register("user-object-group", views.UserObjectGroupUIViewSet)
router.register("zone", views.ZoneUIViewSet)

urlpatterns = [
    path("docs/", RedirectView.as_view(url=static("nautobot_firewall_models/docs/index.html")), name="docs"),
]

urlpatterns += router.urls

nautobot_firewall_models/models/security_policy.py
"""Models for the Firewall app."""
# pylint: disable=duplicate-code, too-many-lines

from django.db import models
from nautobot.apps.constants import CHARFIELD_MAX_LENGTH
from nautobot.core.models.generics import BaseModel, PrimaryModel
from nautobot.extras.models import StatusField
from nautobot.extras.utils import extras_features

from nautobot_firewall_models import choices
from nautobot_firewall_models.utils import get_default_status, model_to_json

###########################
# Core Models
###########################


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "statuses",
    "webhooks",
)
class PolicyRule(PrimaryModel):
    """
    A PolicyRule is a the equivalent of a single in a firewall policy or access list.

    Firewall policies are typically made up of several individual rules.
    """

    name = models.CharField(max_length=CHARFIELD_MAX_LENGTH)
    source_users = models.ManyToManyField(
        blank=True, to="nautobot_firewall_models.UserObject", related_name="policy_rules", verbose_name="Source Users"
    )
    source_user_groups = models.ManyToManyField(
        blank=True,
        to="nautobot_firewall_models.UserObjectGroup",
        related_name="policy_rules",
        verbose_name="Source User Groups",
    )
    source_addresses = models.ManyToManyField(
        blank=True,
        to="nautobot_firewall_models.AddressObject",
        related_name="source_policy_rules",
        verbose_name="Source Addresses",
    )
    source_address_groups = models.ManyToManyField(
        blank=True,
        to="nautobot_firewall_models.AddressObjectGroup",
        related_name="source_policy_rules",
        verbose_name="Source Address Groups",
    )
    source_zone = models.ForeignKey(
        to="nautobot_firewall_models.Zone",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="source_policy_rules",
    )
    source_services = models.ManyToManyField(
        blank=True,
        to="nautobot_firewall_models.ServiceObject",
        related_name="source_policy_rules",
        verbose_name="Source Services",
    )
    source_service_groups = models.ManyToManyField(
        blank=True,
        to="nautobot_firewall_models.ServiceObjectGroup",
        related_name="source_policy_rules",
        verbose_name="Source Service Groups",
    )
    destination_addresses = models.ManyToManyField(
        blank=True,
        to="nautobot_firewall_models.AddressObject",
        related_name="destination_policy_rules",
        verbose_name="Destination Addresses",
    )
    destination_address_groups = models.ManyToManyField(
        blank=True,
        to="nautobot_firewall_models.AddressObjectGroup",
        related_name="destination_policy_rules",
        verbose_name="Destination Address Groups",
    )
    destination_zone = models.ForeignKey(
        to="nautobot_firewall_models.Zone",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="destination_policy_rules",
        verbose_name="Destination Zone",
    )
    destination_services = models.ManyToManyField(
        blank=True,
        to="nautobot_firewall_models.ServiceObject",
        related_name="destination_policy_rules",
        verbose_name="Destination Services",
    )
    destination_service_groups = models.ManyToManyField(
        blank=True,
        to="nautobot_firewall_models.ServiceObjectGroup",
        related_name="destination_policy_rules",
        verbose_name="Destination Service Groups",
    )
    action = models.CharField(choices=choices.ACTION_CHOICES, max_length=CHARFIELD_MAX_LENGTH)
    log = models.BooleanField(default=False)
    status = StatusField(
        on_delete=models.PROTECT,
        related_name="%(app_label)s_%(class)s_related",  # e.g. dcim_device_related
        default=get_default_status,
    )
    applications = models.ManyToManyField(
        blank=True, to="nautobot_firewall_models.ApplicationObject", related_name="policy_rules"
    )
    application_groups = models.ManyToManyField(
        blank=True,
        to="nautobot_firewall_models.ApplicationObjectGroup",
        related_name="policy_rules",
        verbose_name="Application Groups",
    )
    request_id = models.CharField(max_length=CHARFIELD_MAX_LENGTH, blank=True, verbose_name="Request ID")
    description = models.CharField(max_length=1024, blank=True)
    index = models.PositiveSmallIntegerField(null=True, blank=True)

    clone_fields = [
        "source_users",
        "source_user_groups",
        "source_addresses",
        "source_address_groups",
        "source_zone",
        "source_services",
        "source_service_groups",
        "destination_addresses",
        "destination_address_groups",
        "destination_zone",
        "destination_services",
        "destination_service_groups",
        "action",
        "log",
        "status",
    ]
    natural_key_field_names = ["pk"]

    class Meta:
        """Meta class."""

        ordering = ["index", "name"]
        verbose_name_plural = "Policy Rules"

    def rule_details(self):
        """Convience method to convert to more consumable dictionary."""
        row = {}
        row["rule"] = self
        row["source_address_groups"] = self.source_address_groups.all()
        row["source_addresses"] = self.source_addresses.all()
        row["source_users"] = self.source_users.all()
        row["source_user_groupes"] = self.source_user_groups.all()
        row["source_zone"] = self.source_zone
        row["source_services"] = self.source_services.all()
        row["source_service_groups"] = self.source_service_groups.all()

        row["destination_address_groups"] = self.destination_address_groups.all()
        row["destination_addresses"] = self.destination_addresses.all()
        row["destination_zone"] = self.destination_zone
        row["destination_services"] = self.destination_services.all()
        row["destination_service_groups"] = self.destination_service_groups.all()

        row["action"] = self.action
        row["log"] = self.log
        row["status"] = self.status
        row["request_id"] = self.request_id
        return row

    def to_json(self):
        """Convience method to convert to json."""
        return model_to_json(self)

    def __str__(self):
        """Stringify instance."""
        if self.request_id and self.name:
            return f"{self.name} - {self.request_id}"
        if self.name:
            return self.name
        return str(self.id)


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "statuses",
    "webhooks",
)
class Policy(PrimaryModel):
    """
    The overarching model that is the full firewall policy with all underlying rules and child objects.

    Each Policy can be assigned to both devices and to dynamic groups which in turn can assign the policy to a related device.
    """

    description = models.CharField(
        max_length=1024,
        blank=True,
    )
    name = models.CharField(max_length=CHARFIELD_MAX_LENGTH, unique=True)
    policy_rules = models.ManyToManyField(
        to=PolicyRule, blank=True, related_name="policies", verbose_name="Policy Rules"
    )
    assigned_devices = models.ManyToManyField(
        to="dcim.Device",
        through="PolicyDeviceM2M",
        related_name="firewall_policies",
        blank=True,
        verbose_name="Assigned Devices",
    )
    assigned_dynamic_groups = models.ManyToManyField(
        to="extras.DynamicGroup",
        through="PolicyDynamicGroupM2M",
        related_name="firewall_policies",
        blank=True,
        verbose_name="Assigned Dynamic Groups",
    )
    status = StatusField(
        on_delete=models.PROTECT,
        related_name="%(app_label)s_%(class)s_related",  # e.g. dcim_device_related
        default=get_default_status,
    )
    tenant = models.ForeignKey(
        to="tenancy.Tenant",
        on_delete=models.PROTECT,
        related_name="policies",
        blank=True,
        null=True,
    )

    class Meta:
        """Meta class."""

        ordering = ["name"]
        verbose_name_plural = "Policies"

    @property
    def policy_details(self):
        """Convience method to convert to a Python list of dictionaries."""
        data = []
        for policy_rule in self.policy_rules.all():
            data.append(policy_rule.rule_details())
        return data

    def to_json(self):
        """Convience method to convert to json."""
        return model_to_json(self)

    def __str__(self):
        """Stringify instance."""
        return self.name


###########################
# Through Models
###########################


class PolicyDeviceM2M(BaseModel):
    """Through model to add weight to the the Policy & Device relationship."""

    policy = models.ForeignKey("nautobot_firewall_models.Policy", on_delete=models.CASCADE)
    device = models.ForeignKey("dcim.Device", on_delete=models.PROTECT)
    weight = models.PositiveSmallIntegerField(default=100)

    class Meta:
        """Meta class."""

        ordering = ["weight"]
        unique_together = ["policy", "device"]

    def __str__(self):
        """Stringify instance."""
        return f"{self.policy.name} - {self.device.name} - {self.weight}"


class PolicyDynamicGroupM2M(BaseModel):
    """Through model to add weight to the the Policy & DynamicGroup relationship."""

    policy = models.ForeignKey("nautobot_firewall_models.Policy", on_delete=models.CASCADE)
    dynamic_group = models.ForeignKey("extras.DynamicGroup", on_delete=models.PROTECT, verbose_name="Dynamic Group")
    weight = models.PositiveSmallIntegerField(default=100)

    class Meta:
        """Meta class."""

        ordering = ["weight"]
        unique_together = ["policy", "dynamic_group"]

    def __str__(self):

nautobot_firewall_models/views/aerleon_policy.py
"""Aerleon Policy Object Viewsets."""

from nautobot.apps.views import (
    ObjectBulkDestroyViewMixin,
    ObjectChangeLogViewMixin,
    ObjectDestroyViewMixin,
    ObjectDetailViewMixin,
    ObjectListViewMixin,
)
from nautobot.dcim.models import Device
from rest_framework.response import Response

from nautobot_firewall_models import filters, forms, models, tables
from nautobot_firewall_models.api import serializers


class AerleonPolicyUIViewSet(
    ObjectListViewMixin,
    ObjectBulkDestroyViewMixin,
    ObjectDetailViewMixin,
    ObjectChangeLogViewMixin,
    ObjectDestroyViewMixin,
):  # pylint: disable=abstract-method
    """ViewSet for the AerleonPolicy model."""

    bulk_update_form_class = forms.AerleonPolicyBulkEditForm
    filterset_class = filters.AerleonPolicyFilterSet
    filterset_form_class = forms.AerleonPolicyFilterForm
    form_class = forms.AerleonPolicyForm
    queryset = models.AerleonPolicy.objects.all()
    serializer_class = serializers.AerleonPolicySerializer
    table_class = tables.AerleonPolicyTable
    action_buttons = []

    lookup_field = "pk"


class AerleonPolicyDeviceUIViewSet(ObjectDetailViewMixin):  # pylint: disable=abstract-method
    """ViewSet for the AerleonPolicy Device Details."""

    queryset = Device.objects.all()
    lookup_field = "pk"

    def get_template_name(self):
        """Set template name."""
        return "nautobot_firewall_models/aerleonpolicy_details.html"

    def retrieve(self, request, *args, **kwargs):
        """Retrieve a model instance."""
        device = self.get_object()
        policy = models.AerleonPolicy.objects.get(device=device)
        context = {"object": policy, "device": device}
        context["use_new_ui"] = True
        return Response(context)

nautobot_firewall_models/views/capirca_policy.py
"""Capirca Policy Object Viewsets."""

from nautobot.apps.views import (
    ObjectBulkDestroyViewMixin,
    ObjectChangeLogViewMixin,
    ObjectDestroyViewMixin,
    ObjectDetailViewMixin,
    ObjectListViewMixin,
)
from rest_framework.decorators import action
from rest_framework.response import Response

from nautobot_firewall_models import details, filters, forms, models, tables
from nautobot_firewall_models.api import serializers


class CapircaPolicyUIViewSet(
    ObjectListViewMixin,
    ObjectBulkDestroyViewMixin,
    ObjectDetailViewMixin,
    ObjectChangeLogViewMixin,
    ObjectDestroyViewMixin,
):  # pylint: disable=abstract-method
    """ViewSet for the CapircaPolicy model."""

    bulk_update_form_class = forms.CapircaPolicyBulkEditForm
    filterset_class = filters.CapircaPolicyFilterSet
    filterset_form_class = forms.CapircaPolicyFilterForm
    form_class = forms.CapircaPolicyForm
    queryset = models.CapircaPolicy.objects.all()
    serializer_class = serializers.CapircaPolicySerializer
    table_class = tables.CapircaPolicyTable
    action_buttons = []
    object_detail_content = details.capirca_policy

    lookup_field = "pk"

    @action(
        detail=True,
        methods=["get"],
        custom_view_base_action="view",
        custom_view_additional_permissions=["dcim.view_device"],
    )
    def devicedetail(self, request, pk, *args, **kwargs):
        # pylint: disable=invalid-name, arguments-differ, unused-argument
        """Action method to see the full configuration."""
        obj = self.get_object()
        device = obj.device
        context = {"object": obj, "device": device, "active_tab": "devicedetail"}
        return Response(context)

nautobot_firewall_models/views/firewall_config.py
"""Firewall Config Object Viewsets."""

from nautobot.apps.views import NautobotUIViewSet
from rest_framework.decorators import action
from rest_framework.response import Response

from nautobot_firewall_models import details, filters, forms, models, tables
from nautobot_firewall_models.api import serializers


class FirewallConfigUIViewSet(NautobotUIViewSet):
    """ViewSet for the FirewallConfig model."""

    bulk_update_form_class = forms.FirewallConfigBulkEditForm
    filterset_class = filters.FirewallConfigFilterSet
    filterset_form_class = forms.FirewallConfigFilterForm
    form_class = forms.FirewallConfigForm
    queryset = models.FirewallConfig.objects.all()
    serializer_class = serializers.FirewallConfigSerializer
    table_class = tables.FirewallConfigTable
    object_detail_content = details.firewall_config

    lookup_field = "pk"

    @action(detail=True, methods=["get"])
    def devicedetail(self, request, pk, *args, **kwargs):
        # pylint: disable=invalid-name, arguments-differ, unused-argument
        """Action method to see the full configuration."""
        obj = self.get_object()
        device = obj.device
        context = {"object": obj, "device": device, "active_tab": "devicedetail"}
        return Response(context)

nautobot_firewall_models/templates/nautobot_firewall_models/inc/capirca_policy.html
<div class="card">
    <div class="card-header">
        <strong>Capirca Firewall Configurations</strong> - 
        <a href="{% url 'plugins:nautobot_firewall_models:capircapolicy_devicedetail' pk=object.pk %}"><i class="mdi mdi-file-document-outline"></i></a>
        <a href="{% url 'extras:job_run_by_class_path' class_path='nautobot_firewall_models.jobs.RunCapircaJob' %}?device={{ object.pk }}"><i class="mdi mdi-play-circle" title="Execute Capirca Jobs"></i></a>
    </div>
</div> 

nautobot_firewall_models/templates/nautobot_firewall_models/inc/device_policies.html
{% block content %}
<div class="card">
    <div class="card-header"><strong>Security Policies Directly Assigned</strong></div>
    {% if not policies %}
    <div class="card-body">
        <span class="text-secondary">None</span>
    </div>
    {% else %}
    <table class="table table-hover card-body">
        <tr>
            <th>Policy</th>
            <th>Weight</th>
            <th>Type</th>
        </tr>
        <tbody>
            {% for policy in policies %}
                <tr>
                    <td>
                        <a href="{{ policy.policy.get_absolute_url }}">{{ policy.policy }}</a>
                    </td>
                    <td>
                        {{ policy.weight }}
                    </td>
                    <td>
                        Firewall
                    </td>
                </tr>
            {% endfor %}
            {% for policy in nat_policies %}
                <tr>
                    <td>
                        <a href="{{ policy.policy.get_absolute_url }}">{{ policy.nat_policy }}</a>
                    </td>
                    <td>
                        {{ policy.weight }}
                    </td>
                    <td>
                        NAT
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock content %}

nautobot_firewall_models/templates/nautobot_firewall_models/inc/dynamic_group_device_policies.html
{% block content %}
<div class="card">
    <div class="card-header"><strong>Security Policies via Dynamic Groups</strong></div>
    {% if not dynamic_groups %}
    <div class="card-body">
        <span class="text-secondary">None</span>
    </div>
    {% else %}
    <table class="table table-hover card-body">
        <tr>
            <th>Policy</th>
            <th>Weight</th>
            <th>Type</th>
        </tr>
        <tbody>
            {% for group in dynamic_groups %}
                {% for m2m in group.policydynamicgroupm2m_set.all %}
                    <tr>
                        <td>
                            <a href="{{ m2m.policy.get_absolute_url }}">{{ m2m.policy }}</a> via <a href="{{ m2m.dynamic_group.get_absolute_url }}">{{ m2m.dynamic_group }}</a>
                        </td>
                        <td>
                            {{ m2m.weight }}
                        </td>
                        <td>
                            Firewall
                        </td>
                    </tr>
                {% endfor %}
                {% for m2m in group.natpolicydynamicgroupm2m_set.all %}
                    <tr>
                        <td>
                            <a href="{{ m2m.policy.get_absolute_url }}">{{ m2m.nat_policy }}</a> via <a href="{{ m2m.dynamic_group.get_absolute_url }}">{{ m2m.dynamic_group }}</a>
                        </td>
                        <td>
                            {{ m2m.weight }}
                        </td>
                        <td>
                            NAT
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock content %}

nautobot_firewall_models/templates/nautobot_firewall_models/inc/firewall_config.html
<div class="panel panel-default">
    <div class="panel-heading">
        <strong>Firewall Configurations</strong> - 
        <a href="{% url 'plugins:nautobot_firewall_models:firewallconfig_devicedetail' pk=object.pk %}"><i class="mdi mdi-file-document-outline"></i></a>
        <a href="{% url 'extras:job_run_by_class_path' class_path='nautobot_firewall_models.jobs.RunFirewallConfigJob' %}?device={{ object.pk }}"><i class="mdi mdi-play-circle" title="Execute Firewall Config Jobs"></i></a>
    </div>
</div> 

nautobot_firewall_models/templates/nautobot_firewall_models/inc/nat_policy_device_weight.html
{% load helpers %}
<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <strong>Assign NAT Policy Weight to Device</strong>
            </div>
            {% if object.natpolicydevicem2m_set.all %}
                <form action="{% url 'plugins:nautobot_firewall_models:natpolicy_devices' pk=object.id %}" method="post" enctype="multipart/form-data" class="form form-horizontal">
                    {% csrf_token %}
                    <table class="table table-hover card-body">
                        <tr>
                            <th>Weight</th>
                            <th>Device</th>
                        </tr>
                        <tbody>
                            {% for m2m in object.natpolicydevicem2m_set.all %}
                                <tr>
                                    <td>
                                        <input id="device-weight-input{{ forloop.counter }}" type="number" name="{{ m2m.device.id }}" value="{{ m2m.weight }}"{% if not request.user|has_perms:device_weight_tab_perms %} disabled{% endif %}>
                                    </td>
                                    <td>
                                        {{ m2m.device }}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% if request.user|has_perms:device_weight_tab_perms %}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    {% endif %}
                </form>
            {% else %}
                <div class="card-body">
                    <span class="text-secondary">No Devices assigned</span>
                </div>
            {% endif %}
        </div>
    </div>
</div>

nautobot_firewall_models/templates/nautobot_firewall_models/inc/nat_policy_dynamic_group_weight.html
{% load helpers %}
<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <strong>Assign NAT Policy Weight to Dynamic Group</strong>
            </div>
            {% if object.natpolicydynamicgroupm2m_set.all %}
                <form action="{% url 'plugins:nautobot_firewall_models:natpolicy_dynamic-groups' pk=object.id %}" method="post" enctype="multipart/form-data" class="form form-horizontal">
                    {% csrf_token %}
                    <table class="table table-hover card-body">
                        <tr>
                            <th>Weight</th>
                            <th>Dynamic Group</th>
                        </tr>
                        <tbody>
                            {% for m2m in object.natpolicydynamicgroupm2m_set.all %}
                                <tr>
                                    <td>
                                        <input id="dynamicgroup-weight-input{{ forloop.counter }}" type="number" name="{{ m2m.dynamic_group.id }}" value="{{ m2m.weight }}"{% if not request.user|has_perms:dynamicgroup_weight_tab_perms %} disabled{% endif %}>
                                    </td>
                                    <td>
                                        {{ m2m.dynamic_group }}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% if request.user|has_perms:dynamicgroup_weight_tab_perms %}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    {% endif %}
                </form>
            {% else %}
                <div class="card-body">
                    <span class="text-secondary">No Dynamic Groups assigned</span>
                </div>
            {% endif %}
        </div>
    </div>
</div>

nautobot_firewall_models/templates/nautobot_firewall_models/inc/natpolicyrule_tablehead.html
<tr>
    <th style="border: 1px solid #ccc; vertical-align: bottom;" rowspan=3>Index</th>
    <th style="border: 1px solid #ccc; text-align: center;" colspan=4>Original</th>
    <th style="border: 1px solid #ccc; text-align: center;" colspan=4>Translated</th>
    <th style="border: 1px solid #ccc; text-align: center;" colspan=2>Zone</th>
    <th style="border: 1px solid #ccc; vertical-align: bottom;" rowspan=3>Log</th>
</tr>
<tr>
    <th style="border: 1px solid #ccc;" colspan=2>Source</th>
    <th style="border: 1px solid #ccc;" colspan=2>Destination</th>
    <th style="border: 1px solid #ccc;" colspan=2>Source</th>
    <th style="border: 1px solid #ccc;" colspan=2>Destination</th>
    <th style="border: 1px solid #ccc; vertical-align: bottom;" rowspan=2>Source</th>
    <th style="border: 1px solid #ccc; vertical-align: bottom;" rowspan=2>Destination</th>
</tr>
<tr>
    <th style="border: 1px solid #ccc;" >Address</th>
    <th style="border: 1px solid #ccc;" >Service</th>
    <th style="border: 1px solid #ccc;" >Address</th>
    <th style="border: 1px solid #ccc;" >Service</th>
    <th style="border: 1px solid #ccc;" >Address</th>
    <th style="border: 1px solid #ccc;" >Service</th>
    <th style="border: 1px solid #ccc;" >Address</th>
    <th style="border: 1px solid #ccc;" >Service</th>
</tr>

nautobot_firewall_models/templates/nautobot_firewall_models/inc/natpolicyrule_tablerow.html
{% load helpers %}
<tr>
    <td><a href="{{ nat_rule.get_absolute_url }}" title="{{ nat_rule.name }}">{{ nat_rule.index|placeholder|ljust:5 }}</a></td>
    {% if nat_rule.remark %}
        <td colspan="13" style="text-align: center;"><strong>{{ nat_rule }}</strong></td>
    {% else %}
        <td>{% include "./policy_rule_address_object_row.html" with nat=True address=nat_rule.original_source_addresses.all address_group=nat_rule.original_source_address_groups.all %}</td>
        <td>{% include "./policy_rule_service_object_row.html" with nat=True service=nat_rule.original_source_services.all service_group=nat_rule.original_source_service_groups.all %}</td>
        <td>{% include "./policy_rule_address_object_row.html" with nat=True address=nat_rule.original_destination_addresses.all address_group=nat_rule.original_destination_address_groups.all %}</td>
        <td>{% include "./policy_rule_service_object_row.html" with nat=True service=nat_rule.original_destination_services.all service_group=nat_rule.original_destination_service_groups.all %}</td>
        <td>{% include "./policy_rule_address_object_row.html" with nat=True address=nat_rule.translated_source_addresses.all address_group=nat_rule.translated_source_address_groups.all %}</td>
        <td>{% include "./policy_rule_service_object_row.html" with nat=True service=nat_rule.translated_source_services.all service_group=nat_rule.translated_source_service_groups.all %}</td>
        <td>{% include "./policy_rule_address_object_row.html" with nat=True address=nat_rule.translated_destination_addresses.all address_group=nat_rule.translated_destination_address_groups.all %}</td>
        <td>{% include "./policy_rule_service_object_row.html" with nat=True service=nat_rule.translated_destination_services.all service_group=nat_rule.translated_destination_service_groups.all %}</td>
        <td>{% include "./policy_rule_zone_object_row.html" with zone=nat_rule.source_zone %}</td>
        <td>{% include "./policy_rule_zone_object_row.html" with zone=nat_rule.destination_zone %}</td>
        <td>
            {% if nat_rule.log %}
                <span class="text-success"><i class="mdi mdi-check-bold"></i></span>{% else %}<span class="text-danger"><i class="mdi mdi-close-thick"></i></span>
            {% endif %}
        </td>
    {% endif %}
</tr>

nautobot_firewall_models/templates/nautobot_firewall_models/inc/object_policies.html
{% block content %}
<div class="panel panel-default">
    <div class="panel-heading"><strong>Security Policies Directly Assigned</strong></div>
    {% if not policies %}
    <div class="panel-body">
        <span class="text-muted">None</span>
    </div>
    {% else %}
    <table class="table table-hover panel-body">
        <tr>
            <th>Policy</th>
            <th>Weight</th>
            <th>Type</th>
        </tr>
        <tbody>
            {% for policy in policies %}
                <tr>
                    <td>
                        <a href="{{ policy.policy.get_absolute_url }}">{{ policy.policy }}</a>
                    </td>
                    <td>
                        {{ policy.weight }}
                    </td>
                    <td>
                        Firewall
                    </td>
                </tr>
            {% endfor %}
            {% for policy in nat_policies %}
                <tr>
                    <td>
                        <a href="{{ policy.policy.get_absolute_url }}">{{ policy.nat_policy }}</a>
                    </td>
                    <td>
                        {{ policy.weight }}
                    </td>
                    <td>
                        NAT
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock %}

nautobot_firewall_models/templates/nautobot_firewall_models/inc/policy_expanded_rules.html
{% load buttons %}
{% load static %}
{% load custom_links %}
{% load helpers %}
{% load plugins %}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong>Policy Rule Expanded</strong>
            </div>
            <table class="table table-hover card-body">
                {% include "nautobot_firewall_models/inc/policyrule_tablehead.html" %}
                {% comment %}This template is used in two places: the Policy detail view (where object is a Policy instance) and the PolicyRule detail view (where object is a PolicyRule instance). 
                If we're in the Policy detail view, loop through all associated PolicyRules. If we're in the PolicyRule detail view, just display that single rule.{% endcomment %}
                {% if object.policy_rules %}
                    {% with rules=object.policy_rules.all %}
                        {% for rule in rules %}
                            {% include "nautobot_firewall_models/inc/policy_rules_tablerow.html" with rule=rule %}
                        {% endfor %}
                    {% endwith %}
                {% else %}
                    {% include "nautobot_firewall_models/inc/policy_rules_tablerow.html" with rule=object %}
                {% endif %}
            </table>
        </div>
    </div>
</div>