nautobot_firewall_models/urls.py
"""Django urlpatterns declaration for nautobot_firewall_models app."""

from django.templatetags.static import static
from django.urls import path
from django.views.generic import RedirectView
from nautobot.apps.urls import NautobotUIViewSetRouter

from nautobot_firewall_models import views

app_name = "nautobot_firewall_models"
router = NautobotUIViewSetRouter()
router.register("address-object", views.AddressObjectUIViewSet)
router.register("address-object-group", views.AddressObjectGroupUIViewSet)
router.register("application-object", views.ApplicationObjectUIViewSet)
router.register("application-object-group", views.ApplicationObjectGroupUIViewSet)
router.register("capirca-policy", views.CapircaPolicyUIViewSet)
router.register("fqdn", views.FQDNUIViewSet)
router.register("ip-range", views.IPRangeUIViewSet)
router.register("nat-policy", views.NATPolicyUIViewSet)
router.register("nat-policy-rule", views.NATPolicyRuleUIViewSet)
router.register("policy", views.PolicyUIViewSet)
router.register("policy-rule", views.PolicyRuleUIViewSet)
router.register("service-object", views.ServiceObjectUIViewSet)
router.register("service-object-group", views.ServiceObjectGroupUIViewSet)
router.register("user-object", views.UserObjectUIViewSet)
router.register("user-object-group", views.UserObjectGroupUIViewSet)
router.register("zone", views.ZoneUIViewSet)

urlpatterns = [
    path("docs/", RedirectView.as_view(url=static("nautobot_firewall_models/docs/index.html")), name="docs"),
]

urlpatterns += router.urls

nautobot_firewall_models/models/aerleon_policy.py
"""Models for the Aerleon Configurations."""

# pylint: disable=duplicate-code
import logging

from django.db import models
from django.utils.module_loading import import_string
from nautobot.core.models.generics import PrimaryModel
from nautobot.extras.utils import extras_features

from nautobot_firewall_models.constants import PLUGIN_CFG
from nautobot_firewall_models.utils.aerleon import DevicePolicyToAerleon

LOGGER = logging.getLogger(__name__)


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "statuses",
    "webhooks",
)
class AerleonPolicy(PrimaryModel):
    """AerleonPolicy model."""

    device = models.OneToOneField(
        to="dcim.Device", blank=True, null=True, on_delete=models.CASCADE, related_name="aerleon_policy"
    )
    pol = models.TextField(blank=True)
    net = models.TextField(blank=True)
    svc = models.TextField(blank=True)
    cfg = models.TextField(blank=True)

    csv_headers = ["device"]

    class Meta:
        """Meta class."""

        ordering = ["device"]
        verbose_name_plural = "Aerleon Policies"

    def __str__(self):
        """Stringify instance."""
        return f"Aerleon Policy -> {self.device.name}"

    def save(self, *args, **kwargs):
        """Update the firewall rules as updates are made."""
        if not PLUGIN_CFG.get("custom_aerleon"):
            LOGGER.debug("Running standard Aerleon conversion")
            aerleon_obj = DevicePolicyToAerleon(self.device)
            aerleon_obj.get_all_aerleon_cfg()
            self.pol = aerleon_obj.pol_file
            self.svc = aerleon_obj.svc_file
            self.net = aerleon_obj.net_file
            self.cfg = aerleon_obj.cfg_file
        else:
            LOGGER.debug("Running custom conversion from function: `%s`", str(PLUGIN_CFG["custom_aerleon"]))
            self.pol, self.svc, self.net, self.cfg = import_string(PLUGIN_CFG["custom_aerleon"])(self.device)

        super().save(*args, **kwargs)

nautobot_firewall_models/models/zone.py
"""Models for the Firewall app."""
# pylint: disable=duplicate-code

from django.db import models
from nautobot.apps.constants import CHARFIELD_MAX_LENGTH
from nautobot.core.models.generics import PrimaryModel
from nautobot.extras.models import StatusField
from nautobot.extras.utils import extras_features

from nautobot_firewall_models.utils import get_default_status

###########################
# Core Models
###########################


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "statuses",
    "webhooks",
)
class Zone(PrimaryModel):
    """Zones common on firewalls and are typically seen as representations of area (e.g. DMZ trust untrust)."""

    description = models.CharField(
        max_length=1024,
        blank=True,
    )
    name = models.CharField(max_length=CHARFIELD_MAX_LENGTH, unique=True, help_text="Name of the zone (e.g. trust)")
    vrfs = models.ManyToManyField(to="ipam.VRF", blank=True, related_name="zones", verbose_name="VRFs")
    interfaces = models.ManyToManyField(to="dcim.Interface", blank=True, related_name="zones")
    status = StatusField(
        on_delete=models.PROTECT,
        related_name="%(app_label)s_%(class)s_related",  # e.g. dcim_device_related
        default=get_default_status,
    )

    class Meta:
        """Meta class."""

        ordering = ["name"]
        verbose_name_plural = "Zones"

    def __str__(self):
        """Stringify instance."""
        return self.name

nautobot_firewall_models/forms.py
"""Forms for nautobot_firewall_models."""

from django import forms
from nautobot.apps.forms import (
    DynamicModelChoiceField,
    DynamicModelMultipleChoiceField,
    TagFilterField,
    add_blank_choice,
)
from nautobot.dcim.models import Device, Interface
from nautobot.extras.forms import (
    CustomFieldModelCSVForm,
    NautobotBulkEditForm,
    NautobotFilterForm,
    NautobotModelForm,
)
from nautobot.extras.models import DynamicGroup, Tag
from nautobot.ipam.models import VRF, IPAddress, Prefix
from nautobot.tenancy.forms import TenancyFilterForm, TenancyForm
from nautobot.tenancy.models import Tenant

from nautobot_firewall_models import choices, fields, models


class IPRangeFilterForm(NautobotFilterForm):
    """Filter form to filter searches."""

    field_order = ["q", "start_address", "end_address", "vrf"]

    model = models.IPRange
    q = forms.CharField(
        required=False,
        label="Search",
        help_text="Search within Name or Description.",
    )
    start_address = forms.CharField(required=False, label="Starting Address")
    end_address = forms.CharField(required=False, label="Ending Address")
    vrf = DynamicModelChoiceField(queryset=VRF.objects.all(), label="VRF", required=False)


class IPRangeForm(fields.IPRangeFieldMixin, NautobotModelForm):
    """IPRange creation/edit form."""

    vrf = DynamicModelChoiceField(queryset=VRF.objects.all(), label="VRF", required=False)

    class Meta:
        """Meta attributes."""

        model = models.IPRange
        fields = ["vrf", "description", "status", "tags"]


class IPRangeBulkEditForm(NautobotBulkEditForm):
    """IPRange bulk edit form."""

    pk = DynamicModelMultipleChoiceField(queryset=models.IPRange.objects.all(), widget=forms.MultipleHiddenInput)
    description = forms.CharField(required=False)
    # start_address = forms.CharField(required=False)
    # end_address = forms.CharField(required=False)
    vrf = DynamicModelChoiceField(queryset=VRF.objects.all(), required=False)

    class Meta:
        """Meta attributes."""

        nullable_fields = ["description", "vrf"]


class FQDNFilterForm(NautobotFilterForm):
    """Filter form to filter searches."""

    field_order = ["q", "name"]

    model = models.FQDN
    q = forms.CharField(
        required=False,
        label="Search",
        help_text="Search within Name or Description.",
    )
    name = forms.CharField(required=False, label="Name")


class FQDNForm(NautobotModelForm):
    """FQDN creation/edit form."""

    ip_addresses = DynamicModelMultipleChoiceField(queryset=IPAddress.objects.all(), required=False)

    class Meta:
        """Meta attributes."""

        model = models.FQDN
        fields = ["name", "description", "ip_addresses", "status", "tags"]


class FQDNBulkEditForm(NautobotBulkEditForm):
    """FQDN bulk edit form."""

    pk = DynamicModelMultipleChoiceField(queryset=models.FQDN.objects.all(), widget=forms.MultipleHiddenInput)
    description = forms.CharField(required=False)
    ip_addresses = DynamicModelMultipleChoiceField(queryset=IPAddress.objects.all(), required=False)

    class Meta:
        """Meta attributes."""

        nullable_fields = ["description", "ip_addresses"]


class AddressObjectFilterForm(NautobotFilterForm):
    """Filter form to filter searches."""

    field_order = ["q", "name"]

    model = models.AddressObject
    q = forms.CharField(
        required=False,
        label="Search",
        help_text="Search within Name or Description.",
    )
    name = forms.CharField(required=False, label="Name")
    ip_address = DynamicModelChoiceField(queryset=IPAddress.objects.all(), required=False, label="IP Address")
    ip_range = DynamicModelChoiceField(queryset=models.IPRange.objects.all(), required=False, label="IP Range")
    prefix = DynamicModelChoiceField(queryset=Prefix.objects.all(), required=False, label="Prefix")
    fqdn = DynamicModelChoiceField(queryset=models.FQDN.objects.all(), required=False, label="FQDN")


class AddressObjectForm(NautobotModelForm):
    """AddressObject creation/edit form."""

    ip_address = DynamicModelChoiceField(queryset=IPAddress.objects.all(), required=False, label="IP Address")
    ip_range = DynamicModelChoiceField(queryset=models.IPRange.objects.all(), required=False, label="IP Range")
    prefix = DynamicModelChoiceField(queryset=Prefix.objects.all(), required=False, label="Prefix")
    fqdn = DynamicModelChoiceField(queryset=models.FQDN.objects.all(), required=False, label="FQDN")

    class Meta:
        """Meta attributes."""

        model = models.AddressObject
        fields = ["name", "description", "fqdn", "ip_range", "ip_address", "prefix", "status", "tags"]


class AddressObjectBulkEditForm(NautobotBulkEditForm):
    """AddressObject bulk edit form."""

    pk = DynamicModelMultipleChoiceField(queryset=models.AddressObject.objects.all(), widget=forms.MultipleHiddenInput)
    description = forms.CharField(required=False)

    class Meta:
        """Meta attributes."""

        nullable_fields = ["description", "fqdn", "ip_range", "ip_address", "prefix"]


class AddressObjectGroupFilterForm(NautobotFilterForm):
    """Filter form to filter searches."""

    field_order = ["q", "name"]

    model = models.AddressObjectGroup
    q = forms.CharField(
        required=False,
        label="Search",
        help_text="Search within Name or Description.",
    )
    name = forms.CharField(required=False, label="Name")


class AddressObjectGroupForm(NautobotModelForm):
    """AddressObjectGroup creation/edit form."""

    address_objects = DynamicModelMultipleChoiceField(queryset=models.AddressObject.objects.all(), required=False)

    class Meta:
        """Meta attributes."""

        model = models.AddressObjectGroup
        fields = ["name", "description", "address_objects", "status", "tags"]


class AddressObjectGroupBulkEditForm(NautobotBulkEditForm):
    """AddressObjectGroup bulk edit form."""

    pk = DynamicModelMultipleChoiceField(
        queryset=models.AddressObjectGroup.objects.all(), widget=forms.MultipleHiddenInput
    )
    description = forms.CharField(required=False)

    class Meta:
        """Meta attributes."""

        nullable_fields = [
            "description",
        ]


class ApplicationObjectFilterForm(NautobotFilterForm):
    """Filter form to filter searches."""

    field_order = ["q", "name"]

    model = models.ApplicationObject
    q = forms.CharField(
        required=False,
        label="Search",
        help_text="Search within Name or Description.",
    )
    name = forms.CharField(required=False, label="Name")
    category = DynamicModelChoiceField(
        queryset=models.ApplicationObject.objects.all(), required=False, label="Category"
    )


class ApplicationObjectForm(NautobotModelForm):
    """ApplicationObject creation/edit form."""

    class Meta:
        """Meta attributes."""

        model = models.ApplicationObject
        fields = [
            # pylint: disable=duplicate-code
            "name",
            "description",
            "category",
            "subcategory",
            "technology",
            "risk",
            "default_type",
            "default_ip_protocol",
            "status",
        ]


class ApplicationObjectBulkEditForm(NautobotBulkEditForm):
    """ApplicationObject bulk edit form."""

    pk = DynamicModelMultipleChoiceField(
        queryset=models.ApplicationObject.objects.all(), widget=forms.MultipleHiddenInput
    )
    description = forms.CharField(required=False)
    risk = forms.IntegerField(required=False)
    technology = forms.CharField(required=False)
    category = forms.CharField(required=False)
    subcategory = forms.CharField(required=False)

    class Meta:
        """Meta attributes."""

        nullable_fields = [
            "description",
            "default_ip_protocol",
            "default_type",
            "technology",
            "category",
            "subcategory",
        ]


class ApplicationObjectGroupFilterForm(NautobotFilterForm):
    """Filter form to filter searches."""

    field_order = ["q", "name"]

    model = models.ApplicationObjectGroup
    q = forms.CharField(
        required=False,
        label="Search",
        help_text="Search within Name or Description.",
    )
    name = forms.CharField(required=False, label="Name")


class ApplicationObjectGroupForm(NautobotModelForm):
    """ApplicationObjectGroup creation/edit form."""

    application_objects = DynamicModelMultipleChoiceField(queryset=models.ApplicationObject.objects.all())

    class Meta:
        """Meta attributes."""

        model = models.ApplicationObjectGroup
        fields = ["name", "description", "application_objects", "status", "tags"]


class ApplicationObjectGroupBulkEditForm(NautobotBulkEditForm):
    """ApplicationObjectGroup bulk edit form."""

    pk = DynamicModelMultipleChoiceField(
        queryset=models.ApplicationObjectGroup.objects.all(), widget=forms.MultipleHiddenInput
    )
    description = forms.CharField(required=False)

    class Meta:
        """Meta attributes."""

        nullable_fields = [
            "description",
        ]


class ServiceObjectFilterForm(NautobotFilterForm):
    """Filter form to filter searches."""

    field_order = ["q", "name"]

    model = models.ServiceObject
    q = forms.CharField(
        required=False,
        label="Search",
        help_text="Search within Name or Description.",
    )
    name = forms.CharField(required=False, label="Name")
    port = forms.IntegerField(required=False)
    ip_protocol = forms.ChoiceField(choices=add_blank_choice(choices.IP_PROTOCOL_CHOICES), required=False)


class ServiceObjectForm(NautobotModelForm):
    """ServiceObject creation/edit form."""

    port = forms.CharField(
        help_text="Must be a single integer representation of port OR single port range without spaces (e.g. 80 or 8080-8088)",
        required=False,
    )

    class Meta:

nautobot_firewall_models/views/capirca_policy.py
"""Capirca Policy Object Viewsets."""

from nautobot.apps.views import (
    ObjectBulkDestroyViewMixin,
    ObjectChangeLogViewMixin,
    ObjectDestroyViewMixin,
    ObjectDetailViewMixin,
    ObjectListViewMixin,
)
from rest_framework.decorators import action
from rest_framework.response import Response

from nautobot_firewall_models import details, filters, forms, models, tables
from nautobot_firewall_models.api import serializers


class CapircaPolicyUIViewSet(
    ObjectListViewMixin,
    ObjectBulkDestroyViewMixin,
    ObjectDetailViewMixin,
    ObjectChangeLogViewMixin,
    ObjectDestroyViewMixin,
):  # pylint: disable=abstract-method
    """ViewSet for the CapircaPolicy model."""

    bulk_update_form_class = forms.CapircaPolicyBulkEditForm
    filterset_class = filters.CapircaPolicyFilterSet
    filterset_form_class = forms.CapircaPolicyFilterForm
    form_class = forms.CapircaPolicyForm
    queryset = models.CapircaPolicy.objects.all()
    serializer_class = serializers.CapircaPolicySerializer
    table_class = tables.CapircaPolicyTable
    action_buttons = []
    object_detail_content = details.capirca_policy

    lookup_field = "pk"

    @action(
        detail=True,
        methods=["get"],
        custom_view_base_action="view",
        custom_view_additional_permissions=["dcim.view_device"],
    )
    def devicedetail(self, request, pk, *args, **kwargs):
        # pylint: disable=invalid-name, arguments-differ, unused-argument
        """Action method to see the full configuration."""
        obj = self.get_object()
        device = obj.device
        context = {"object": obj, "device": device, "active_tab": "devicedetail"}
        return Response(context)

nautobot_firewall_models/views/zone.py
"""Zone Object Viewsets."""

from nautobot.apps.views import NautobotUIViewSet

from nautobot_firewall_models import details, filters, forms, models, tables
from nautobot_firewall_models.api import serializers


class ZoneUIViewSet(NautobotUIViewSet):
    """ViewSet for the Zone model."""

    bulk_update_form_class = forms.ZoneBulkEditForm
    filterset_class = filters.ZoneFilterSet
    filterset_form_class = forms.ZoneFilterForm
    form_class = forms.ZoneForm
    queryset = models.Zone.objects.all()
    serializer_class = serializers.ZoneSerializer
    table_class = tables.ZoneTable
    object_detail_content = details.zone

    lookup_field = "pk"

nautobot_firewall_models/templates/nautobot_firewall_models/aerleonpolicy_retrieve.html
{% extends 'generic/object_retrieve.html' %}
{% load helpers %}
{% load buttons %}
{% load plugins %}
{% load fw_tags %}

{% block buttons %}
        {% plugin_buttons object %}
        {% if perms.nautobot_firewall_models.delete_aerleonpolicy %}
            {% delete_button object %}
        {% endif %}
{% endblock buttons %}

{% block content_left_page %}
<div class="panel panel-default">
    <div class="panel-heading">
        <strong>Aerleon Object <a href="{% url 'plugins:nautobot_firewall_models:aerleonpolicy_devicedetail' pk=object.device.pk %}"><i class="mdi mdi-file-document-outline"></i></a></strong>
    </div>
    <table class="table table-hover panel-body attr-table">
        <tr>
            <td>Configuration</td>
            <td><pre>{{ object.cfg|render_truncate|placeholder }}</pre></td>
        </tr>
        <tr>
            <td>Policy File</td>
            <td><pre>{{ object.pol|render_truncate|placeholder }}</pre></td>
        </tr>
        <tr>
            <td>Services File</td>
            <td><pre>{{ object.svc|render_truncate|placeholder }}</pre></td>
        </tr>
        <tr>
            <td>Network File</td>
            <td><pre>{{ object.net|render_truncate|placeholder }}</pre></td>
        </tr>
    </table>
</div>

{% endblock %}

nautobot_firewall_models/templates/nautobot_firewall_models/serviceobject_create.html
{% extends "generic/object_create.html" %}
{% load form_helpers %}
{% load helpers %}

{% block javascript %}
  {% if not editing %}
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Duplicate Service Objects</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">The following Service Object(s) were found with the same IP Protocol and Port. Please confirm you would like to create a duplicated object.</div>
          <div class="modal-body">
            <ul id="duplicate_results"></ul>
          </div>
          <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <input type="hidden" name="name" id="confirm_name">
            <input type="hidden" name="description" id="confirm_description">
            <input type="hidden" name="port" id="confirm_port">
            <input type="hidden" name="ip_protocol" id="confirm_ip_protocol">
            <input type="hidden" name="status" id="confirm_status">
            <select name="tags" id="confirm_tags" multiple hidden></select>
            <div class="modal-footer">
              <button type="submit" name="_create" class="btn btn-primary">Create</button>
              <button type="submit" name="_addanother" class="btn btn-primary">Create and Add Another</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script>
      $(".form-horizontal").submit(function(event) {
        event.preventDefault();
        $("button[name='_create']").prop("disabled", true);
        $("button[name='_addanother']").prop("disabled", true);
        var base_url = "{% url 'plugins:nautobot_firewall_models:serviceobject_list' %}";
        var name = $("#id_name").val();
        var description = $("#id_description").val();
        var port = $("#id_port").val();
        var ip_protocol = $("#id_ip_protocol").val();
        var status = $("#id_status").val();
        var tags = $("#id_tags").children().clone();
        $.get(
          "{% url 'plugins-api:nautobot_firewall_models-api:serviceobject-list' %}",
          {port: port, ip_protocol: ip_protocol}
        ).done(function(data){
          if (data.count > 0) {
            for (let i = 0; i < data.results.length; i++) {
              $("#duplicate_results").append(
                $("<li>").append(
                  $("<a>").attr("href", base_url+data.results[i].id+"/").html(data.results[i].name+": "+data.results[i].ip_protocol+" "+data.results[i].port)
                )
              )
            }
            $("#confirm_name").val(name);
            $("#confirm_description").val(description);
            $("#confirm_port").val(port);
            $("#confirm_ip_protocol").val(ip_protocol);
            $("#confirm_status").val(status);
            $("#confirm_tags").html(tags);
            $("button[name='_create']").prop("disabled", false);
            $("button[name='_addanother']").prop("disabled", false);
            $("#exampleModal").modal();
          } else {
            event.currentTarget.submit();
          }
        });
      });
    </script>
    {% endif %}
{% endblock javascript %}

nautobot_firewall_models/templates/nautobot_firewall_models/serviceobject_edit.html
{% extends "generic/object_create.html" %}
{% load form_helpers %}
{% load helpers %}

{% block javascript %}
  {% if not editing %}
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Duplicate Service Objects</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">The following Service Object(s) were found with the same IP Protocol and Port. Please confirm you would like to create a duplicated object.</div>
          <div class="modal-body">
            <ul id="duplicate_results"></ul>
          </div>
          <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <input type="hidden" name="name" id="confirm_name">
            <input type="hidden" name="description" id="confirm_description">
            <input type="hidden" name="port" id="confirm_port">
            <input type="hidden" name="ip_protocol" id="confirm_ip_protocol">
            <input type="hidden" name="status" id="confirm_status">
            <select name="tags" id="confirm_tags" multiple hidden></select>
            <div class="modal-footer">
              <button type="submit" name="_create" class="btn btn-primary">Create</button>
              <button type="submit" name="_addanother" class="btn btn-primary">Create and Add Another</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script>
      $(".form-horizontal").submit(function(event) {
        event.preventDefault();
        $("button[name='_create']").prop("disabled", true);
        $("button[name='_addanother']").prop("disabled", true);
        var base_url = "{% url 'plugins:nautobot_firewall_models:serviceobject_list' %}";
        var name = $("#id_name").val();
        var description = $("#id_description").val();
        var port = $("#id_port").val();
        var ip_protocol = $("#id_ip_protocol").val();
        var status = $("#id_status").val();
        var tags = $("#id_tags").children().clone();
        $.get(
          "{% url 'plugins-api:nautobot_firewall_models-api:serviceobject-list' %}",
          {port: port, ip_protocol: ip_protocol}
        ).done(function(data){
          if (data.count > 0) {
            for (let i = 0; i < data.results.length; i++) {
              $("#duplicate_results").append(
                $("<li>").append(
                  $("<a>").attr("href", base_url+data.results[i].id+"/").html(data.results[i].name+": "+data.results[i].ip_protocol+" "+data.results[i].port)
                )
              )
            }
            $("#confirm_name").val(name);
            $("#confirm_description").val(description);
            $("#confirm_port").val(port);
            $("#confirm_ip_protocol").val(ip_protocol);
            $("#confirm_status").val(status);
            $("#confirm_tags").html(tags);
            $("button[name='_create']").prop("disabled", false);
            $("button[name='_addanother']").prop("disabled", false);
            $("#exampleModal").modal();
          } else {
            event.currentTarget.submit();
          }
        });
      });
    </script>
    {% endif %}
{% endblock javascript %}

nautobot_firewall_models/templates/nautobot_firewall_models/serviceobject_update.html
{% extends "generic/object_create.html" %}
{% load form_helpers %}
{% load helpers %}

{% block javascript %}
  {% if not editing %}
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Duplicate Service Objects</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">The following Service Object(s) were found with the same IP Protocol and Port. Please confirm you would like to create a duplicated object.</div>
          <div class="modal-body">
            <ul id="duplicate_results"></ul>
          </div>
          <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <input type="hidden" name="name" id="confirm_name">
            <input type="hidden" name="description" id="confirm_description">
            <input type="hidden" name="port" id="confirm_port">
            <input type="hidden" name="ip_protocol" id="confirm_ip_protocol">
            <input type="hidden" name="status" id="confirm_status">
            <select name="tags" id="confirm_tags" multiple hidden></select>
            <div class="modal-footer">
              <button type="submit" name="_create" class="btn btn-primary">Create</button>
              <button type="submit" name="_addanother" class="btn btn-primary">Create and Add Another</button>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script>
      $("form[action='']").on("submit", function(event) {
        event.preventDefault();
        $("button[name='_create']").prop("disabled", true);
        $("button[name='_addanother']").prop("disabled", true);
        var base_url = "{% url 'plugins:nautobot_firewall_models:serviceobject_list' %}";
        var name = $("#id_name").val();
        var description = $("#id_description").val();
        var port = $("#id_port").val();
        var ip_protocol = $("#id_ip_protocol").val();
        var status = $("#id_status").val();
        var tags = $("#id_tags").children().clone();
        $.get(
          "{% url 'plugins-api:nautobot_firewall_models-api:serviceobject-list' %}",
          {port: port, ip_protocol: ip_protocol}
        ).done(function(data){
          if (data.count > 0) {
            $("#duplicate_results").empty();
            for (let i = 0; i < data.results.length; i++) {
              $("#duplicate_results").append(
                $("<li>").append(
                  $("<a>").attr("href", base_url+data.results[i].id+"/").html(data.results[i].name+": "+data.results[i].ip_protocol+" "+data.results[i].port)
                )
              )
            }
            $("#confirm_name").val(name);
            $("#confirm_description").val(description);
            $("#confirm_port").val(port);
            $("#confirm_ip_protocol").val(ip_protocol);
            $("#confirm_status").val(status);
            $("#confirm_tags").html(tags);
            $("button[name='_create']").prop("disabled", false);
            $("button[name='_addanother']").prop("disabled", false);
            const modalWindow = new bootstrap.Modal(document.getElementById("exampleModal"));
            modalWindow.show();
          } else {
            event.currentTarget.submit();
          }
        });
      });
    </script>
    {% endif %}
{% endblock javascript %}